### ISSUE TITLE
New default tab: arrival times for closest stop.

### ISSUE THREAD

**Issue by revan** [churichard/ru-direct#5]
With the "nearest stop" logic written, it might make sense to add a tab to the main page that just shows the arrival times for that stop (or a few closest stops, like [this guy did](http://www.ruthereyetapp.com/)).

He's also got a persistent notification for the nearest stop, but that feels like too much.

I can go ahead and start this if you'd like!

**Comment by churichard** [comment]
Thanks for the suggestion, but I don't think this feature is necessary, and I'd like to keep the main screen as clean as possible.
