### ISSUE TITLE
Keep tags updated and remove unnecessary branches

### ISSUE THREAD

**Issue by adityadalal924** [churichard/ru-direct#6]
Tags, not branches, should be used for immutable references.

```bash
# make new tags
git tag 1.0.3 fafc5d0
git tag 1.0.4 291de51
git push origin --tags

# delete local branches
git branch -d v1.0.1
git branch -d v1.0.2
git branch -d v1.0.3
git branch -d v1.0.4

# delete remote branches
git push origin :v1.0.1
git push origin :v1.0.2
git push origin :v1.0.3
git push origin :v1.0.4
```

You may also want to sign or describe releases, as shown [here](http://alblue.bandlem.com/2011/04/git-tip-of-week-tags.html).

**Comment by churichard** [comment]
Thanks for the tip! I wasn't aware of the usefulness of tags before, but now I am.
