### ISSUE TITLE
Make Route view offline-ready

### ISSUE THREAD

**Issue by adityadalal924** [churichard/ru-direct#7]
Looks like you can cache the tiles on first load and return them from your own `TileProvider` - would be useful to mimize data usage/speed up that view when on mobile data. Seems like a good idea because the views are fairly static anyway.

See: http://stackoverflow.com/questions/14784841/tileprovider-using-local-tiles

**Comment by churichard** [comment]
I believe Google Maps already caches the map tiles. You can test this by loading a map, closing the app, turning on Airplane Mode, then opening the app and loading a map again.

**Comment by adityadalal924** [comment]
Invalid check, the app errors out.  (It should cache instead of displaying no info)

http://imgur.com/j5MizDv

**Comment by churichard** [comment]
You can still access the routes and maps through the "All" tab, albeit with no times. Active routes obviously can't be shown without Internet.
